Test, alter "email" program slightly

diff --git a/bench/Makefile b/bench/Makefile
--- a/bench/Makefile
+++ b/bench/Makefile
@@ -3,6 +3,7 @@ PYTHON_BINDIR=python/src
 PERL_BINDIR=perl/src
 TCL_BINDIR=tcl/src
 RE2J_BINDIR=re2j/build/jar
+SED_BINDIR=sed/src
 
 SOURCES = $(wildcard re2/src/*.cpp) $(wildcard python/src/*.py)
 
@@ -13,11 +14,15 @@ HASEDDIR = hased_src
 REPG = ../dist/build/repg/repg
 DATA_DIR = ../test/data
 
+red='\033[0;31m'
+green='\033[0;32m'
+NC='\033[0m' # No Color
+
 # Through unimaginable hackery, we can get a hashmap-like thing in make.
 # Attach test input file to the programs, to check that the RE2 C++
 # programs called <NAME> are equivalent to the Hased programs <NAME>.has
 testinput.patho2         := $(DATA_DIR)/strings/ab_lines.txt
-testinput.csv_project3   := $(DATA_DIR)/csv/csv_format1.csv
+testinput.csv_project3   := $(DATA_DIR)/csv/csv_format1.sample.csv
 testinput.as             := $(DATA_DIR)/strings/as_small.txt
 testinput.simple_id      := $(DATA_DIR)/strings/ab_lines_small.txt
 testinput.issuu_json2sql := $(DATA_DIR)/issuu/sample.json
@@ -49,7 +54,7 @@ equality_check: data_check $(HASSOURCES_OBJECTS)
 	@if [ -f $(RE2_BINDIR)/$(*F) ];  then \
 		printf "RE2 == Hased?     " ; \
 		$(RE2_BINDIR)/$(*F) < ${testinput.$(*F)} > $(*F).out 2> /dev/null  ; \
-		shasum -c $(*F).sha ; \
+		shasum -c $(*F).sha &> /dev/null && echo ${green}OK${NC} || echo ${red}FAIL${NC} ; \
 	else\
 		echo "Can't find $(RE2_BINDIR)/$(*F).  Skipping.";\
 	fi
@@ -57,7 +62,7 @@ equality_check: data_check $(HASSOURCES_OBJECTS)
 	@if [ -f $(PYTHON_BINDIR)/$(*F).py ]; then \
 		printf "Python == Hased?  " ; \
 		python $(PYTHON_BINDIR)/$(*F).py < ${testinput.$(*F)} > $(*F).out 2> /dev/null ; \
-		shasum -c $(*F).sha ; \
+		shasum -c $(*F).sha &> /dev/null && echo ${green}OK${NC} || echo ${red}FAIL${NC} ; \
 	else \
 		echo "Can't find $(PYTHON_BINDIR)/$(*F).py.  Skipping."; \
 	fi
@@ -65,7 +70,7 @@ equality_check: data_check $(HASSOURCES_OBJECTS)
 	@if [ -f $(PERL_BINDIR)/$(*F).pl ]; then \
 		printf "Perl == Hased?    " ; \
 		perl $(PERL_BINDIR)/$(*F).pl < ${testinput.$(*F)} > $(*F).out 2> /dev/null ; \
-		shasum -c $(*F).sha ; \
+		shasum -c $(*F).sha &> /dev/null && echo ${green}OK${NC} || echo ${red}FAIL${NC} ; \
 	else \
 		echo "Can't find $(PERL_BINDIR)/$(*F).pl  Skipping."; \
 	fi
@@ -74,7 +79,7 @@ equality_check: data_check $(HASSOURCES_OBJECTS)
 	@if [ -f $(TCL_BINDIR)/$(*F).tcl ]; then \
 		printf "Tcl == Hased?     " ; \
 		tclsh $(TCL_BINDIR)/$(*F).tcl < ${testinput.$(*F)} > $(*F).out 2> /dev/null ; \
-		shasum -c $(*F).sha ; \
+		shasum -c $(*F).sha &> /dev/null && echo ${green}OK${NC} || echo ${red}FAIL${NC} ; \
 	else \
 		echo "Can't find $(TCL_BINDIR)/$(*F).tcl  Skipping."; \
 	fi
@@ -83,10 +88,20 @@ equality_check: data_check $(HASSOURCES_OBJECTS)
 	@if [ -f $(RE2J_BINDIR)/$(*F).jar ]; then \
 		printf "RE2/J == Hased?   " ; \
 		java -jar $(RE2J_BINDIR)/$(*F).jar < ${testinput.$(*F)} > $(*F).out 2> /dev/null ; \
-		shasum -c $(*F).sha ; \
+		shasum -c $(*F).sha &> /dev/null && echo ${green}OK${NC} || echo ${red}FAIL${NC} ; \
 	else \
 		echo "Can't find $(RE2J_BINDIR)/$(*F).jar  Skipping."; \
 	fi
+
+	@if [ -f $(SED_BINDIR)/$(*F).sh ]; then \
+		printf "Sed == Hased?     " ; \
+		bash $(SED_BINDIR)/$(*F).sh < ${testinput.$(*F)} > $(*F).out 2> /dev/null ; \
+		shasum -c $(*F).sha &> /dev/null && echo ${green}OK${NC} || echo ${red}FAIL${NC} ; \
+	else \
+		echo "Can't find $(SED_BINDIR)/$(*F).sh  Skipping."; \
+	fi
+
+
 
 
 	rm $(*F).out $(*F).sha has_$(*F)
